server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html;

    client_max_body_size 64M;

    logging_to_stderr on; # Mempermudah tracking log via `docker logs`

    location / {
        # Mengarahkan semua request ke index.php bawaan Laravel
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$; # Memisahkan path info dengan aman
        include fastcgi_params;
        fastcgi_pass app:9000; # Memastikan melempar ke service 'app' port 9000
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~* \.(?:css|js|map|ico|png|jpg|jpeg|gif|svg|woff2?|ttf|eot)$ {
        expires 30d;
        access_log off;
    }
}